# -*- coding: utf-8 -*-
"""Tech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l8iS9lGZRDwlRc2TfIljaNr5eEMyAcMB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.dates import date2num
import mplfinance as mpf  # For candlestick charts

# Helper function to prepare candlestick data
def prepare_candlestick_data(data):
    candlestick_data = []
    for entry in data:
        candlestick_data.append((
            entry['date'],  # Date
            entry['open'],  # Open
            entry['high'],  # High
            entry['low'],   # Low
            entry['close']  # Close
        ))
    return candlestick_data

# Function to plot candlestick chart with indicators
def plot_trading_chart(data, sma, ema, buy_signals, sell_signals):
    df = pd.DataFrame(data)
    df['Date'] = pd.to_datetime(df['date'])
    df.set_index('Date', inplace=True)

    # Add indicators to DataFrame
    df['SMA'] = sma
    df['EMA'] = ema

    # Plot candlestick chart
    apds = [
        mpf.make_addplot(df['SMA'], color='blue', label='SMA'),
        mpf.make_addplot(df['EMA'], color='red', label='EMA')
    ]
    mpf.plot(
        df,
        type='candle',
        addplot=apds,
        title="TradingView-like Chart",
        style='charles',
        volume=True,
        figratio=(12, 6),
        datetime_format='%Y-%m-%d',
        warn_too_much_data=10000
    )

# Example raw data
raw_data = [
    {'date': '2024-12-01', 'open': 1200, 'high': 1250, 'low': 1180, 'close': 1220, 'volume': 500000},
    {'date': '2024-11-30', 'open': 1210, 'high': 1230, 'low': 1190, 'close': 1200, 'volume': 450000},
    # Add more data here
]

# Process data
candlestick_data = prepare_candlestick_data(raw_data)

# Example SMA and EMA values
sma = [1215, 1217]
ema = [1216, 1218]

# Example buy/sell signals (indexes where buy/sell occur)
buy_signals = [1]
sell_signals = [0]

# Plot the chart
plot_trading_chart(raw_data, sma, ema, buy_signals, sell_signals)



